# StyLua config (Luau, safe keys)
syntax = "Luau"            # <- use this, not lua_version
column_width = 120
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
