--!strict

--====================================================--
--  Script: [FeatureFlags]
--  Location: [ReplicatedStorage/Shared/Config/]
--  Version: 1.0.0
--  Last Updated: 2025-09-06
--  Author: Rhocwud Games
--
--  Description:
--      [specifies the enabled or disabled state of certain features or settings]
--
--  Change Log:
--      v1.0.0 - Initial version
--
--====================================================--

return {
	NewMovementEnabled = true,
	NewCombatEnabled   = false,
	DebugUI            = true,
}
