--!strict

--====================================================--
--  Script: [TargetLockController]
--  Location: [StarterPlayer/StarterPlayerScripts/]
--  Version: 1.0.0
--  Last Updated: 2025-09-06
--  Author: Rhocwud Games
--
--  Description:
--      [Future Target lock system]
--		
--  Change Log:
--      v1.0.0 - Initial version
--
--====================================================--
local M = {}
function M:GetLockedTarget() return nil end
function M:Start(...) end
return M
