# .github/workflows/generate-projectfilelinks.yml
# Auto-generate docs/ProjectFileLinks.txt listing all .luau files under Explorer/
# Runs on every push to main (adjust branches if you use a different default)
name: Generate ProjectFileLinks

on:
  push:
    branches: [ "main" ]

# Grant the workflow permission to update repository contents (allows commit/push)
permissions:
  contents: write

jobs:
  generate-links:
    runs-on: ubuntu-latest
    env:
      # Derive repo owner and name from the context
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      BRANCH: main
      ROOT: Explorer
      OUT: docs/ProjectFileLinks.txt

    steps:
      - name: Checkout repo (with token to allow push)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create docs folder if missing
        run: mkdir -p docs

      - name: Generate ProjectFileLinks.txt
        run: |
          echo "# Auto-generated ProjectFileLinks.txt" > "$OUT"
          echo "# Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$OUT"
          echo "" >> "$OUT"
          # Find all .luau files under the ROOT folder and create raw.githubusercontent.com URLs
          find "$ROOT" -type f -name "*.luau" | sort | while read -r f; do
            fname=$(basename "$f")
            rel="${f#${ROOT}/}"           # path relative to Explorer/
            # Build raw URL
            url="https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/$ROOT/$rel"
            printf "%s | %s | %s | %s\n" "$fname" "$rel" "$url" "$(date +%F)" >> "$OUT"
          done
          echo "Wrote $OUT with $(wc -l < $OUT) lines."

      - name: Commit & push ProjectFileLinks.txt (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT"
          if git diff --staged --quiet; then
            echo "No changes to $OUT; nothing to commit."
          else
            git commit -m "chore: regenerate ProjectFileLinks.txt"
            git push origin "$BRANCH"
          fi
