# .github/workflows/publish-lua-gist.yml
name: Publish .luau Gist (private snapshot)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  snapshot-and-publish:
    runs-on: ubuntu-latest
    env:
      GIST_DESCRIPTION: "RizzCity .luau snapshot (private gist)"
      ROOT: Explorer

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Python 3 available
        run: python3 --version

      - name: Install Python dependencies (requests)
        run: python3 -m pip install --user requests

      - name: Run create_gist.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python3 scripts/create_gist.py
